include_keywords:
  - "人工智能"
  - "大模型"
  - "LLM"
  - "ChatGPT"
  - "自动驾驶"
  - "特斯拉"
  - "SpaceX"
  - "火箭"
  - "太空探索"
  - "指数"
  - "A股"
  - "港股"
  - "美股"
  - "研报"
  - "异动"
  - "涨停"
  - "跌停"
  - "新股"
  - "申购"
  - "龙虎榜"
  - "食品安全"
  - "添加剂"
  - "顺丰"
  - "顺丰快递"
  - "AI大模型"
  - "DeepSeek"
  - "中美谈判"
  - "中国"
  - "日本"
  - "韩国"
  - "隆基绿能"
  - "光伏"
  - "五粮液"
  - "白酒"
  - "消费"
  - "大摩"
  - "花旗"
  - "美联储"
  - "证券"
  - "高盛"
  - "摩根士丹利"
  - "瑞银"
  - "汇丰"
  - "天猫"
  - "阿里"
  - "京东"
  - "电商"
  - "直播间"
  - "成都"
  - "宜宾"
  - "李佳琦"
  - "李佳琦直播间"
  - "Omega"
  - "vitaminD"
  - "meta"
  - "china"
exclude_keywords:
  - "广告"
  - "推广"
  - "营销"
  - "优惠券"
  - "打折"
  - "促销"
  - "免费"
  - "赚钱"
  - "兼职"